HelloDjango/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('myapp.urls')),
    path('', include('core.urls')),
    path('myapp/', include('myapp.urls')),
    path('users/', include('users.urls')),
    path('messaging/', include('messaging.urls')),
    path('anketa/', include('anketa.urls')),
    path('account/login/', LoginView.as_view(template_name='users/login.html'), name='login'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

anketa/urls.py
from django.urls import path
from .views import AnketaView, success_view


app_name = 'anketa'

urlpatterns = [
    path('start/', AnketaView.as_view(), name='start'),
    path('success/', success_view, name='success'),
]

core/urls.py
from django.urls import path
from . import views

# app_name = 'core'

urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.index, name='about'),  # Заглушка для страницы "О нас"
    path('accounts/login/', views.index, name='login'),  # Заглушка для входа
    path('anketa/', views.index, name='anketa'),  # Заглушка для анкеты
    path('contacts/', views.index, name='contacts'),  # Заглушка для контактов
    path('content/<int:pk>/', views.menu_content, name='menu-content'),
    path('pages/<slug:slug>/', views.page_detail, name='page-detail'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Медицинский портал "Кардиология, Наро-Фоминск"</title>
    <link rel="shortcut icon"
              type="image/x-icon"
              href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'global/css/menu.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=PT+Serif:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.6.0/css/all.css">
</head>
<body>
    <main class="content" id="main-content">
        {% block content %}{% endblock %}
    </main>
    {% include 'includes/footer.html' %}
    <script src="{% static 'global/js/menu.js' %}"></script >
</body>
{% comment %} <script>
    // Проверяем наличие pers_id в сессии
    if (window.location.pathname === "{% url 'anketa:start' %}" 
        && "{{ request.session.pers_id }}") {
        window.location.href = "{% url 'anketa:success' %}";
    }
</script> {% endcomment %}
</html>

templates/base0.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Приветствие</title>
    <link rel="shortcut icon"
    type="image/x-icon"
    href="{% static 'admin/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'myapp/css/style.css' %}">
</head>
<body>
    <main class="content" id="main-content">
        {% block content %}{% endblock %}
    </main>
</body>
</html>